#!/usr/bin/env python3
"""
Setup script for TraderAgent - Safely configure your OpenAI API key
"""

import os
import getpass
from pathlib import Path

def setup_api_key():
    """Safely configure OpenAI API key for local development"""
    
    print("🤖 TraderAgent Setup")
    print("=" * 50)
    print("This script will help you configure your OpenAI API key securely.")
    print("Your API key will be stored locally and never committed to git.")
    print()
    
    # Check if API key is already set
    current_key = os.getenv('OPENAI_API_KEY')
    if current_key and current_key != 'your_openai_api_key_here':
        print(f"✅ API key already configured: {current_key[:8]}...")
        return True
    
    # Get API key from user
    print("📝 Please enter your OpenAI API key:")
    print("   (You can find this at: https://platform.openai.com/api-keys)")
    print("   (Your input will be hidden for security)")
    print()
    
    api_key = getpass.getpass("OpenAI API Key: ").strip()
    
    if not api_key:
        print("❌ No API key provided. Exiting.")
        return False
    
    if not api_key.startswith('sk-'):
        print("⚠️  Warning: API key should start with 'sk-'")
        confirm = input("Continue anyway? (y/N): ").lower()
        if confirm != 'y':
            print("❌ Setup cancelled.")
            return False
    
    # Save to .env.dev file
    env_file = Path('.env.dev')
    
    try:
        with open(env_file, 'w') as f:
            f.write(f"# OpenAI API Key for TraderAgent\n")
            f.write(f"# Generated by setup script on {os.getenv('DATE', 'unknown date')}\n")
            f.write(f"OPENAI_API_KEY={api_key}\n")
        
        print(f"✅ API key saved to {env_file}")
        print("🔒 This file is git-ignored and will not be committed.")
        print()
        
        # Test the API key
        print("🧪 Testing API key...")
        os.environ['OPENAI_API_KEY'] = api_key
        
        try:
            import openai
            client = openai.OpenAI(api_key=api_key)
            # Quick test - just validate the key format
            print("✅ API key format looks valid!")
            print()
            print("🚀 Setup complete! You can now run:")
            print("   python main.py --paper        # Paper trading")
            print("   python scripts/run_tests.py   # Run tests")
            print()
            return True
            
        except Exception as e:
            print(f"⚠️  Could not validate API key: {e}")
            print("   The key has been saved, but please verify it works.")
            return True
            
    except Exception as e:
        print(f"❌ Error saving API key: {e}")
        return False

if __name__ == "__main__":
    setup_api_key()